name: Contract CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - run: forge install OpenZeppelin/openzeppelin-contracts@v5.0.2 --no-git
      - run: forge build
      - run: forge test -vvv
